karazeh: kzh::hasher Class Reference
kzh::hasher Class Reference abstract
#include <hasher.hpp>
Classes
struct digest_rc
Public Member Functions
hasher (string_t const &name)
virtual ~hasher ()
virtual digest_rc hex_digest (string_t const &data) const =0
virtual digest_rc hex_digest (std::ifstream &src) const =0
virtual digest_rc hex_digest (path_t const &path) const =0
string_t const & name () const
Protected Attributes
string_t name_
Constructor & Destructor Documentation
kzh::hasher::hasher (string_t const & name) inline
virtual kzh::hasher::~hasher () inline virtual
Member Function Documentation
virtual digest_rc kzh::hasher::hex_digest (string_t const & data) const pure virtual
digests can be calculated directly off raw data
Implemented in kzh::md5_hasher.
Referenced by kzh::create_operation::commit(), kzh::update_operation::deploy(), kzh::create_operation::deploy(), kzh::downloader::fetch(), kzh::version_manifest::get_current_version(), kzh::create_operation::has_deployed(), kzh::update_operation::stage(), and TEST_CASE().
virtual digest_rc kzh::hasher::hex_digest (std::ifstream & src) const pure virtual
digests can be calculated off data in a valid file stream
Implemented in kzh::md5_hasher.
virtual digest_rc kzh::hasher::hex_digest (path_t const & path) const pure virtual
Implemented in kzh::md5_hasher.
string_t const& kzh::hasher::name () const inline
Member Data Documentation
string_t kzh::hasher::name_ protected
The documentation for this class was generated from the following file:
include/karazeh/hasher.hpp