karazeh: src/operations/__tests__/create.test.cpp File Reference
create.test.cpp File Reference
#include "catch.hpp"
#include "karazeh/karazeh.hpp"
#include "karazeh/config.hpp"
#include "karazeh/operations/create.hpp"
#include "karazeh/hashers/md5_hasher.hpp"
#include "karazeh/release_manifest.hpp"
#include "test_utils.hpp"
#include <boost/filesystem.hpp>
#include "fakeit.hpp"
Macros
#define STUB_HEX_DIGEST ConstOverloadedMethod(hasherSpy, hex_digest, hasher::digest_rc(const path_t&))
#define STUB_IS_READABLE ConstOverloadedMethod(spy, is_readable, bool(path_t const&))
#define STUB_IS_WRITABLE ConstOverloadedMethod(spy, is_writable, bool(path_t const&))
#define STUB_MAKE_EXECUTABLE ConstOverloadedMethod(spy, make_executable, bool(path_t const&))
#define STUB_MOVE ConstOverloadedMethod(spy, move, bool(path_t const&, path_t const&))
#define STUB_REMOVE_DIRECTORY ConstOverloadedMethod(spy, remove_directory, bool(path_t const&))
#define STUB_REMOVE_FILE ConstOverloadedMethod(spy, remove_file, bool(path_t const&))
Functions
TEST_CASE ("create_operation")
Macro Definition Documentation
#define STUB_HEX_DIGEST ConstOverloadedMethod(hasherSpy, hex_digest, hasher::digest_rc(const path_t&))
Referenced by TEST_CASE().
#define STUB_IS_READABLE ConstOverloadedMethod(spy, is_readable, bool(path_t const&))
Referenced by TEST_CASE().
#define STUB_IS_WRITABLE ConstOverloadedMethod(spy, is_writable, bool(path_t const&))
Referenced by TEST_CASE().
#define STUB_MAKE_EXECUTABLE ConstOverloadedMethod(spy, make_executable, bool(path_t const&))
Referenced by TEST_CASE().
#define STUB_MOVE ConstOverloadedMethod(spy, move, bool(path_t const&, path_t const&))
Referenced by TEST_CASE().
#define STUB_REMOVE_DIRECTORY ConstOverloadedMethod(spy, remove_directory, bool(path_t const&))
Referenced by TEST_CASE().
#define STUB_REMOVE_FILE ConstOverloadedMethod(spy, remove_file, bool(path_t const&))
Referenced by TEST_CASE().
Function Documentation
TEST_CASE ("create_operation")
References kzh::KARAZEH_EXPORT::cache_path, kzh::create_operation::commit(), kzh::create_operation::deploy(), kzh::hasher::digest_rc::digest, kzh::KARAZEH_EXPORT::downloader, kzh::create_operation::dst_path, kzh::file_manager::exists(), kzh::KARAZEH_EXPORT::file_manager, kzh::KARAZEH_EXPORT::hasher, kzh::hasher::hex_digest(), kzh::release_manifest::id, kzh::file_manager::is_directory(), kzh::create_operation::is_executable, kzh::create_operation::marked_for_deletion(), kzh::create_operation::rollback(), kzh::KARAZEH_EXPORT::root_path, kzh::downloader::set_retry_count(), kzh::create_operation::src_checksum, kzh::create_operation::src_size, kzh::create_operation::src_uri, kzh::create_operation::stage(), kzh::STAGE_FILE_EXISTS, kzh::STAGE_OK, kzh::STAGE_UNAUTHORIZED, STUB_HEX_DIGEST, STUB_IS_READABLE, STUB_IS_WRITABLE, STUB_MAKE_EXECUTABLE, STUB_MOVE, STUB_REMOVE_DIRECTORY, STUB_REMOVE_FILE, and kzh::hasher::digest_rc::valid.