karazeh: src/__tests__/patcher.test.cpp File Reference
patcher.test.cpp File Reference
#include "catch.hpp"
#include "karazeh/karazeh.hpp"
#include "karazeh/patcher.hpp"
#include "karazeh/path_resolver.hpp"
#include "karazeh/version_manifest.hpp"
#include "test_utils.hpp"
#include <boost/filesystem.hpp>
Functions
TEST_CASE ("Patcher","[Patcher_JSON]")
Function Documentation
TEST_CASE ("Patcher" , "" [Patcher_JSON])
References kzh::patcher::apply_update(), kzh::KARAZEH_EXPORT::file_manager, kzh::path_resolver::get_cache_path(), kzh::version_manifest::get_release(), kzh::path_resolver::get_root_path(), kzh::KARAZEH_EXPORT::host, kzh::version_manifest::load_from_uri(), kzh::version_manifest::load_release_from_uri(), kzh::file_manager::remove_directory(), kzh::path_resolver::resolve(), kzh::KARAZEH_EXPORT::root_path, and kzh::STAGE_OK.