karazeh: src/path_resolver.cpp File Reference
path_resolver.cpp File Reference
#include "karazeh/path_resolver.hpp"
#include <CoreFoundation/CoreFoundation.h>
#include <Windows.h>
Namespaces
kzh
Functions
static path_t kzh::locate_bin_directory (const logger *, bool verbose)
static path_t kzh::locate_root_directory (const path_t &)
static std::string macBundlePath ()
Function Documentation
static std::string macBundlePath () static
karazeh – the library for patching software
Copyright (C) 2011-2016 by Ahmad Amireh ahmad.nosp@m.@ami.nosp@m.reh.n.nosp@m.et
This program is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
References kzh::locate_bin_directory(), and kzh::locate_root_directory().
Referenced by kzh::locate_bin_directory().