karazeh: src/__tests__/version_manifest.test.cpp File Reference
version_manifest.test.cpp File Reference
#include "catch.hpp"
#include "karazeh/karazeh.hpp"
#include "karazeh/version_manifest.hpp"
#include "karazeh/path_resolver.hpp"
#include "test_utils.hpp"
Functions
TEST_CASE ("VersionManifest")
Function Documentation
TEST_CASE ("VersionManifest")
References kzh::KARAZEH_EXPORT::file_manager, kzh::version_manifest::get_available_updates(), kzh::version_manifest::get_current_version(), kzh::version_manifest::get_release(), kzh::version_manifest::get_release_count(), kzh::file_manager::load_file(), kzh::version_manifest::load_from_string(), kzh::release_manifest::operations, kzh::version_manifest::parse_release(), and kzh::KARAZEH_EXPORT::root_path.